## editable
default_theme: "lux"

# list of packages used by this website
# author, package name, package link
thanks:
  - { author: twbs, name: bootstrap, link: "https://github.com/twbs/bootstrap" }
  - {
      author: ivanvotti,
      name: font-awesome-svg,
      link: "https://github.com/ivanvotti/font-awesome-svg",
    }
  - {
      author: thomaspark,
      name: bootswatch,
      link: "https://github.com/thomaspark/bootswatch",
    }
  - { author: pexels.com, name: poster images, link: "https://www.pexels.com" }
  - {
      author: dracula,
      name: rouge-dracula,
      link: "https://github.com/dracula/gh-pages/blob/master/_sass/rouge-dracula.scss",
    }

# -----------------------------------------------------------------------------------------
# non-editable
# default values
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      poster: "blog.jpg"
      category: "misc"
      tags: []
      desc: ""

# exclude files from hosting
exclude:
  - LICENSE
  - TODO.md
  - README.md

# plugin required for hosting
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap

# Markdown Configuration
kramdown:
  input: GFM # github flavoured markdown
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
