# list of packages used by this website
# author, package name, package link
thanks:
  - { author: twbs, name: bootstrap, link: "https://github.com/twbs/bootstrap" }
  - {
      author: ivanvotti,
      name: font-awesome-svg,
      link: "https://github.com/ivanvotti/font-awesome-svg",
    }

# exclude files from hosting
exclude:
  - LICENSE
  - TODO.md

# plugin required by hoster
plugins:
  - jekyll-feed
  - jekyll-github-metadata
