# thanks to
thanks:
  - { author: twbs, name: bootstrap, link: "https://github.com/twbs/bootstrap" }
  - {
      author: ivanvotti,
      name: font-awesome-svg,
      link: "https://github.com/ivanvotti/font-awesome-svg",
    }

# other config
exclude: 
  - LICENSE
  - TODO.md
plugins:
  - jekyll-feed
  - jekyll-github-metadata 
