# list of packages used by this website
# author, package name, package link
thanks:
  - { author: twbs, name: bootstrap, link: "https://github.com/twbs/bootstrap" }
  - {
      author: ivanvotti,
      name: font-awesome-svg,
      link: "https://github.com/ivanvotti/font-awesome-svg",
    }

# default values 
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      poster: ""
      category: "misc"
      tags: []
      desc: "" 

# exclude files from hosting
exclude:
  - LICENSE
  - TODO.md
  - README.md

# plugin required for hosting
plugins:
  - jekyll-feed
  - jekyll-github-metadata
